<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="dims"
    value="${xacro.load_yaml('$(find hamals_robot_description)/config/robot_dimensions.yaml')}" />

  <!-- Drive wheel geometry (AUTHORITATIVE ground reference) -->
  <xacro:property name="wheel_radius"
    value="${dims['wheels']['radius']}"/>

  <xacro:property name="wheel_center_z"
    value="${dims['wheels']['z_offset'] * -1.0}"/>

  <!-- Caster geometry -->
  <xacro:property name="caster_radius"
    value="${dims['casters']['radius']}"/>

  <xacro:property name="front_x"
    value="${dims['casters']['front_x']}"/>
  <xacro:property name="rear_x"
    value="${dims['casters']['rear_x']}"/>

  <!-- Ground plane from wheel -->
  <xacro:property name="ground_z"
    value="${wheel_center_z - wheel_radius}"/>

  <!-- Caster center exactly touching ground -->
  <xacro:property name="caster_z"
    value="${ground_z + caster_radius}"/>

  <!-- FRONT CASTER -->
  <link name="front_caster_link">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="caster_gray"/>
    </visual>
  </link>

  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster_link"/>
    <origin xyz="${front_x} 0 ${caster_z}"/>
  </joint>

  <!-- REAR CASTER -->
  <link name="rear_caster_link">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="caster_gray"/>
    </visual>
  </link>

  <joint name="rear_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_caster_link"/>
    <origin xyz="${rear_x} 0 ${caster_z}"/>
  </joint>

</robot>